150 extend non native policies
NilFoundation/zkllvm-blueprint pull request #163
Opened 2023-06-30 17:09 UTC by CblPOK-git

2023-07-03 17:33 UTC, Iluvmagick commented
Unrelated, but: why do ordinary addition/multiplication/division depend on NonNativePolicyType? It doesn't seem to be used there at all.
I understand why would **non-native** variants require a non-native policy specification, but it being present as a template parameter for **native** ones confuses me.

2023-07-03 17:51 UTC, Iluvmagick commented
`blueprint_algebra_fields_plonk_non_native_reduction_test` does not build for me.
```c++
In file included from libs/crypto3/libs/blueprint/test/algebra/fields/plonk/non_native/reduction.cpp:40:
libs/crypto3/libs/blueprint/include/nil/blueprint/components/algebra/fields/plonk/non_native/reduction.hpp:75:92: error: no type named 'non_native_var_type' in 'nil::blueprint::detail::basic_non_native_policy_field_type<typename crypto3::algebra::curves::pallas::base_field_type, typename crypto3::algebra::curves::ed25519::scalar_field_type>'
                    typename non_native_policy_type::template field<operating_field_type>::non_native_var_type output;
```
You need to update the type for <pallas::base, ed25519::scalar> too.

2023-07-03 18:00 UTC, Iluvmagick requested changes
Reduction test should be working and we shouldn't have to reimplement the same functions for each policy we create.

2023-07-04 08:03 UTC, CblPOK-git commented on include/nil/blueprint/basic_non_native_policy.hpp
> +                static native_field_type::value_type get_i_th_chunk(non_native_field_type::value_type input,
Fixed reduction test, now works.
Copy-paste of function is done on purpose, we are going to re-write this thing https://github.com/NilFoundation/zkllvm-blueprint/issues/164 , it was fast way to implement needed feature. Not worth spending time optimizing the code that will be re-written soon.

2023-07-04 08:14 UTC, CblPOK-git commented
> why do ordinary addition/multiplication/division depend on NonNativePolicyType

In the future policies will be used in native components too, just added and not implemented yet

2023-07-04 09:52 UTC, nkaskov approved these changes

2023-07-04 09:53 UTC, nkaskov approved these changes

2023-07-04 10:14 UTC, Iluvmagick approved these changes

2023-07-04 10:22 UTC, merged