interpolation coefs components and tests
NilFoundation/zkllvm-blueprint pull request #258
Opened 2023-11-03 13:11 UTC by ayashunsky

These are simple components for computing coefficients of linear and quadratic interpolations

2023-11-21 13:30 UTC, Iluvmagick requested changes
The components are good!
But please add the test to `run_tests.yml` so that they run in our CI, and rebase on master.

2023-11-22 07:27 UTC, ayashunsky commented on include/nil/blueprint/components/algebra/fields/plonk/quadratic_interpolation.hpp
> +                T det3(std::array<T,9> a) {
initializer_list doesn't support the [] operator unfortunately. For now, leave it as it is.

2023-11-22 07:27 UTC, ayashunsky commented on test/algebra/fields/plonk/interpolation.cpp
> +    // one explicitely failing test
Fixed

2023-11-22 19:14 UTC, Iluvmagick commented
Either something went wrong during the rebase here, or github is bugged.
Only your four commits should be visible in the pull request.
Somehow the changes are duplicating?
Unsure what is going on.

2023-11-23 14:15 UTC, Iluvmagick approved these changes

2023-11-23 14:16 UTC, merged